name: check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [clang16]

    steps:
    - uses: actions/checkout@v3

    - run: |
        ldconfig -p

    - name: install libtinfo5
      # clang tools load libtinfo5 for color diagnostics but `ubuntu-latest`
      # runners already have `libtinfo.so.6` installed. We just create a
      # symlink since it's faster than installing libtinfo5.
      # https://github.com/circleci/circleci-images/issues/430#issuecomment-522602495
      run: |
        sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          test \
          --config=${{ matrix.toolchain }} \
          --features=${{ matrix.feature }} \
          //...
